name: ci

on:
  pull_request:
  push:

env:
  GO_VERSION: 1.17.7

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 #v2.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: build
        run: go build -o apko ./cmd/apko/main.go

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 #v2.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: test
        run: go test ./...
